export const GET_GROUP_INFO_SUCCESS = "GET_GROUP_INFO_SUCCESS";

export const GET_GROUP_INFO_FAIL = "GET_GROUP_INFO_FAIL";

export const FIND_GROUPS = "FIND_GROUPS";

export const UPDATE_GROUP_INFO = "UPDATE_GROUP_INFO";
