export const GET_USER_GROUPS = "GET_USER_GROUPS";

export const GET_USER_GROUPS_FAIL = "GET_USER_GROUPS_FAIL";

export const FIND_GROUPS = "FIND_GROUPS";

export const UPDATE_GROUPS_LIST = "UPDATE_GROUPS_LIST";
