export const USER_SIGNUP = "USER_SIGNUP";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGIN_WITH_GOOGLE = "USER_LOGIN_WITH_GOOGLE";
export const USER_LOGIN_WITH_GOOGLE_SUCCESS = "USER_LOGIN_WITH_GOOGLE_SUCCESS";
export const USER_LOGIN_WITH_GOOGLE_FAIL = "USER_LOGIN_WITH_GOOGLE_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const GET_USER_FROM_STORAGE = "GET_USER_FROM_STORAGE";
