export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const GET_USER_FROM_STORAGE = "GET_USER_FROM_STORAGE";

export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";

export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
